#!/bin/bash

#Il faut mettre ci-dessous le répertoire que l'on veut sauvegarder
saveall=~/Téléchargements/Wiki/

if [ `date "+%u"` = 5  ] ; then
	cd $saveall
	tar cf backup_`date "+%Y-%m-%d"`.tar *
	mv backup_`date "+%Y-%m-%d"`.tar $HOMEbackup_`date "+%Y-%m-%d"`.tar
	echo "Nous sommes vendredi la sauvegarde du répertoire courant hebdomadaire est effectué."

else 
	cd $saveall
	mkdir .backup_temp 
	tar -xvf ~/backup_all.tar -C .backup_temp
	diff -q backup_all.tar .backup_temp
	echo "Sauvegarde journalière effectué"
	rm -rf .backup_temp
fi;

echo -e "Dans quel répertoire ce trouve votre fichier ?\nVeuillez rentrez le chemin à partir de $HOME :"; read rep
cd ~/$rep
pwd 

echo -e "Quel est votre fichier/dossier que vous voulez sauvegarder :"
ls --color=auto

read folder
tar cvf backup__$folder.tar $folder
