#!/bin/bash

#Il faut mettre ci-dessous le répertoire que l'on veut sauvegarder
saveall=~/Téléchargements/Wiki/
dat=backup_`date "+%Y-%m-%d"`.tar
temprep=''
ok=0

if [ `date "+%u"` = 5  ] ; then
	if [ "`ls $HOME | grep $dat`" != "$dat" ] ; then 
		cd $saveall
		tar cf backup_`date "+%Y-%m-%d"`.tar *
		mv backup_`date "+%Y-%m-%d"`.tar $HOME
		echo "Nous sommes vendredi la sauvegarde du répertoire courant hebdomadaire est effectué."

	else
		echo "Backup déjà à jour"
	fi
else 
	cd $HOME
	if [ "`ls | grep backup_jour.tar`" != "backup_jour.tar" ] ; then
		cd $saveall
		tar cf backup_jour.tar * && mv backup_jour.tar $HOME
		echo "Première sauvegarde journalière effectué"
	else
		tar df backup_jour.tar -C $saveall
		rm backup_jour.tar
		cd $saveall
                tar cf backup_jour.tar * && mv backup_jour.tar $HOME
		echo "Sauvegarde journalière effectué"
	fi;
fi;

cd $HOME
echo -e "Dans quel répertoire ce trouve votre fichier ?\nVeuillez rentrez le chemin à partir de $HOME :"; read rep

while [ $ok -ne 1 ] ; do
	if [ "`cd ~/$rep && pwd`" = "$HOME/$rep" ] ; then 
		temprep=$rep
		((ok+=1))
	else
		echo "Ce dossier n'existe pas"
		read rep
	fi
done 
cd ~/$rep && pwd 

echo -e "Quel est votre fichier/dossier que vous voulez sauvegarder :"
ls --color=auto
read folder

tar cvf backup__$folder.tar $folder
