#!/bin/bash
rep=Musique
rep2=Music

#Dispo quand pour une bière
#sudo dnf install youtube-dl -y

#Il est temps de changer mon grand
#sudo apt install youtube-dl ffmpeg -y

#btw i use arch
#sudo pacman -S youtube-dl ffmpeg

if [ `echo ${PWD##*/}` = "$rep" ] || [ `echo ${PWD##*/}` =  "$rep2" ] ;  then 
	echo "Vous êtes déjà dans $rep"
elif [ -e ~/$rep ] || [ -e ~/$rep2 ] ; then
	cd ~/$rep || cd ~/$rep2
else
	mkdir ̃ /$rep
	cd ~/$rep
fi;

read -p 'Liens URL de la vidéo : ' link
youtube-dl $link -x --output "%(title)s.%(ext)s" --audio-format mp3
ls --color=auto
