#!/bin/bash
rep=Musique

#Dispo quand pour une bière
#sudo dnf install youtube-dl -y

#Il est temps de changer mon grand
#sudo apt install youtube-dl ffmpeg -y

#btw i use arch
#sudo pacman -S youtube-dl ffmpeg

if [ `echo ${PWD##*/}` = "$rep" ] ;  then 
	echo "Vous êtes déjà dans $rep"
elif [ -e ~/$rep  ] ; then
	cd ~/$rep
else
	mkdir ̃ /$rep
	cd ~/$rep
fi;

read -p 'Liens URL de la vidéo : ' link
youtube-dl $link -x --audio-format mp3
ls --color=auto
